version: v3

tasks:
  dev:
    env:
      CONFIG_PATH: ./bin/config.yaml
      ENDPOINT: localhost:8001
    cmds:
      - nodemon -q -e 'go' --signal SIGTERM --exec "task build && ./bin/server || exit 0"

  dev:local:
    env:
      CONFIG_PATH: ./bin/config.yaml
      ENDPOINT: localhost:8001
    cmds:
      - nodemon -q -e 'go' --signal SIGTERM --exec "task build && ./bin/server --mode=local || exit 0"

  dev:hub:
    env:
      CONFIG_PATH: ./bin/config.yaml
      ENDPOINT: localhost:8001
    cmds:
      - nodemon -q -e 'go' --signal SIGTERM --exec "task build && ./bin/server --mode=hub || exit 0"

  scp:
    preconditions:
      - sh: '[ -n "{{.IP}}" ]'
        msg: 'var IP must have a value'
    cmds:
      - ssh raspberry@{{.IP}} 'rm -f /home/raspberry/server'
      - scp ./bin/server-arm raspberry@{{.IP}}:/home/raspberry/server
      - scp ./k3s-setup.sh raspberry@{{.IP}}:/home/raspberry/k3s-setup.sh
      - ssh raspberry@{{.IP}} 'sudo reboot'

  build:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build  -ldflags="-s -w -X github.com/kloudlite/iot-devices/constants.Debug=false" -o ./bin/server main.go

  build:arm:
    env:
      CGO_ENABLED: 0
      GOARCH: arm64
    cmds:
      - go build -o ./bin/server-arm main.go
      - upx ./bin/server-arm
